name: Generar animación de contribuciones (snake)

on:
  schedule:
    - cron: "0 0 * * *"   # se regenera cada día a medianoche UTC
  workflow_dispatch:        # te permite ejecutarlo manualmente también
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generar el SVG del snake
        uses: Platane/snk@v3
        with:
          github_user_name: CarlosG9615
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Subir el SVG a la rama "output"
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
